name: ""          # 应用名称
type: ""          # 应用类型
version: "1.0"    # 版本号

deps: []          # 依赖项
env: {}           # 环境变量

steps:            # 安装步骤
  pre: []         # 安装前步骤
  main: []        # 主要安装步骤
  post: []        # 安装后步骤

cmd: ""          # 启动命令